# Generated by Django 6.0.4 on 2026-04-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original', models.URLField(max_length=1000)),
            ],
        ),
    ]
